import { PartnerService } from '@/lib/types/partners';

export const partnerServices: PartnerService[] = [
    {
        id: 'partner_001',
        slug: 'housing',
        title: 'Housing & Accommodation',
        shortDescription: 'Find your perfect student home with verified listings and move-in support.',
        longDescription: 'Our comprehensive housing service helps international students find safe, affordable, and convenient accommodation near their university. From shared apartments to private studios, we handle everything from search to move-in.',
        icon: 'Home',
        benefits: [
            'Verified and safe housing options',
            'Close proximity to universities',
            'No hidden fees or scams',
            'Multilingual support team',
            'Flexible lease terms for students',
        ],
        tiers: [
            {
                id: 'housing_starter',
                name: 'Starter',
                price: 99,
                description: 'Basic housing search assistance',
                deliveryDays: 14,
                features: [
                    'Access to housing listings database',
                    'Email support',
                    'Basic neighborhood guide',
                    '5 property recommendations',
                ],
            },
            {
                id: 'housing_survival',
                name: 'Survival',
                price: 199,
                description: 'Essential housing package',
                deliveryDays: 10,
                features: [
                    'Everything in Starter',
                    '10 property recommendations',
                    'Virtual property tours',
                    'Lease review assistance',
                    'Chat support',
                ],
            },
            {
                id: 'housing_comfort',
                name: 'Comfort',
                price: 349,
                description: 'Full-service housing solution',
                deliveryDays: 7,
                isPopular: true,
                features: [
                    'Everything in Survival',
                    'Unlimited property recommendations',
                    'In-person property visits',
                    'Lease negotiation support',
                    'Move-in coordination',
                    'Priority support',
                ],
            },
            {
                id: 'housing_vip',
                name: 'VIP',
                price: 599,
                description: 'Premium concierge service',
                deliveryDays: 5,
                features: [
                    'Everything in Comfort',
                    'Dedicated housing advisor',
                    'Airport pickup to housing',
                    'Furniture package assistance',
                    'Utility setup included',
                    '30-day post-move support',
                    '24/7 emergency line',
                ],
            },
        ],
    },
    {
        id: 'partner_002',
        slug: 'banking',
        title: 'Banking & Account Activation',
        shortDescription: 'Open your bank account hassle-free with expert guidance.',
        longDescription: 'Navigate the complexities of opening a bank account in a new country. We help you choose the right bank, prepare documents, schedule appointments, and activate your account quickly.',
        icon: 'Building2',
        benefits: [
            'Expert guidance on bank selection',
            'Document preparation assistance',
            'Appointment scheduling',
            'Card activation support',
            'Student-friendly account options',
        ],
        tiers: [
            {
                id: 'banking_starter',
                name: 'Starter',
                price: 29,
                description: 'DIY banking guide',
                deliveryDays: 3,
                features: [
                    'Bank comparison guide',
                    'Document checklist',
                    'Email support',
                    'FAQ access',
                ],
            },
            {
                id: 'banking_survival',
                name: 'Survival',
                price: 59,
                description: 'Guided account opening',
                deliveryDays: 5,
                features: [
                    'Everything in Starter',
                    'Personalized bank recommendation',
                    'Document verification',
                    'Appointment booking',
                    'Chat support',
                ],
            },
            {
                id: 'banking_comfort',
                name: 'Comfort',
                price: 99,
                description: 'Full banking setup',
                deliveryDays: 3,
                isPopular: true,
                features: [
                    'Everything in Survival',
                    'Accompanied bank visit',
                    'Card activation assistance',
                    'Mobile banking setup',
                    'International transfer guide',
                    'Priority support',
                ],
            },
            {
                id: 'banking_vip',
                name: 'VIP',
                price: 179,
                description: 'Premium banking concierge',
                deliveryDays: 2,
                features: [
                    'Everything in Comfort',
                    'Dedicated banking advisor',
                    'Multiple account setup',
                    'Investment account guidance',
                    'Credit card application help',
                    'Tax ID registration',
                    '24/7 support',
                ],
            },
        ],
    },
    {
        id: 'partner_003',
        slug: 'fast-track',
        title: 'Fast-Track Processing',
        shortDescription: 'Reduce your wait time from 45 days to just 15 days.',
        longDescription: 'Our fast-track service expedites your document processing, visa applications, and administrative procedures. What normally takes 45 days can be completed in just 15 days with our priority handling.',
        icon: 'Zap',
        benefits: [
            'Significantly reduced processing time',
            'Priority handling of documents',
            'Dedicated case manager',
            'Real-time status updates',
            'Express delivery options',
        ],
        tiers: [
            {
                id: 'fasttrack_starter',
                name: 'Starter',
                price: 149,
                description: 'Basic expedited processing',
                deliveryDays: 30,
                features: [
                    'Reduced to 30 days (from 45)',
                    'Document preparation guide',
                    'Status tracking portal',
                    'Email updates',
                ],
            },
            {
                id: 'fasttrack_survival',
                name: 'Survival',
                price: 249,
                description: 'Fast processing',
                deliveryDays: 21,
                features: [
                    'Reduced to 21 days',
                    'Everything in Starter',
                    'Priority queue placement',
                    'Document review & correction',
                    'Weekly status calls',
                ],
            },
            {
                id: 'fasttrack_comfort',
                name: 'Comfort',
                price: 399,
                description: 'Express processing',
                deliveryDays: 15,
                isPopular: true,
                features: [
                    'Reduced to 15 days',
                    'Everything in Survival',
                    'Dedicated case manager',
                    'Rush document handling',
                    'Direct liaison with authorities',
                    'Priority support',
                ],
            },
            {
                id: 'fasttrack_vip',
                name: 'VIP',
                price: 699,
                description: 'Ultra-fast VIP processing',
                deliveryDays: 10,
                features: [
                    'Reduced to 10 days',
                    'Everything in Comfort',
                    'Executive case manager',
                    'Expedited at every stage',
                    'Personal document courier',
                    'Guaranteed timeline',
                    '24/7 direct line',
                ],
            },
        ],
    },
    {
        id: 'partner_004',
        slug: 'subsidy',
        title: 'Subsidy Claim Assistance',
        shortDescription: 'Navigate subsidy claims with expert guidance and support.',
        longDescription: 'Don\'t miss out on financial support you\'re entitled to. Our experts guide you through the entire subsidy claim process, from eligibility check to successful claim submission and follow-up.',
        icon: 'Receipt',
        benefits: [
            'Eligibility assessment',
            'Complete documentation support',
            'Claim form assistance',
            'Follow-up with authorities',
            'Maximize your benefits',
        ],
        tiers: [
            {
                id: 'subsidy_starter',
                name: 'Starter',
                price: 49,
                description: 'Self-service claim guide',
                deliveryDays: 7,
                features: [
                    'Eligibility checker tool',
                    'Document checklist',
                    'Step-by-step guide',
                    'Email support',
                ],
            },
            {
                id: 'subsidy_survival',
                name: 'Survival',
                price: 99,
                description: 'Guided claim submission',
                deliveryDays: 10,
                features: [
                    'Everything in Starter',
                    'Personal eligibility review',
                    'Document preparation help',
                    'Form filling assistance',
                    'Chat support',
                ],
            },
            {
                id: 'subsidy_comfort',
                name: 'Comfort',
                price: 179,
                description: 'Full claim management',
                deliveryDays: 14,
                isPopular: true,
                features: [
                    'Everything in Survival',
                    'Complete claim handling',
                    'Authority liaison',
                    'Appeal support if needed',
                    'Status tracking',
                    'Priority support',
                ],
            },
            {
                id: 'subsidy_vip',
                name: 'VIP',
                price: 299,
                description: 'Premium claim concierge',
                deliveryDays: 7,
                features: [
                    'Everything in Comfort',
                    'Dedicated subsidy advisor',
                    'Multi-subsidy applications',
                    'Expedited processing',
                    'Financial optimization review',
                    'Annual claim management',
                    '24/7 support',
                ],
            },
        ],
    },
    {
        id: 'partner_005',
        slug: 'sim-transport',
        title: 'SIM & Transportation',
        shortDescription: 'Stay connected and mobile from day one.',
        longDescription: 'Get set up with a mobile plan and transportation pass as soon as you arrive. We help you compare options, get the best student deals, and activate everything so you\'re ready to go.',
        icon: 'Smartphone',
        benefits: [
            'Best student mobile plans',
            'Immediate SIM activation',
            'Transit pass procurement',
            'Multi-city transport options',
            'Data and calling packages',
        ],
        tiers: [
            {
                id: 'simtransport_starter',
                name: 'Starter',
                price: 25,
                description: 'Basic connectivity setup',
                deliveryDays: 1,
                features: [
                    'SIM card procurement',
                    'Basic data plan activation',
                    'Carrier comparison guide',
                    'Email support',
                ],
            },
            {
                id: 'simtransport_survival',
                name: 'Survival',
                price: 49,
                description: 'Connected & mobile',
                deliveryDays: 2,
                features: [
                    'Everything in Starter',
                    'Monthly transit pass',
                    'Student discount application',
                    'Route planning assistance',
                    'Chat support',
                ],
            },
            {
                id: 'simtransport_comfort',
                name: 'Comfort',
                price: 89,
                description: 'Full mobility package',
                deliveryDays: 2,
                isPopular: true,
                features: [
                    'Everything in Survival',
                    'Premium data plan',
                    'International calling setup',
                    'Bike/scooter rental guidance',
                    'Transport app setup',
                    'Priority support',
                ],
            },
            {
                id: 'simtransport_vip',
                name: 'VIP',
                price: 149,
                description: 'Premium mobility concierge',
                deliveryDays: 1,
                features: [
                    'Everything in Comfort',
                    'Airport SIM delivery',
                    '3-month transit pass',
                    'Rideshare account setup',
                    'Car rental assistance',
                    'Multi-city transport card',
                    '24/7 support',
                ],
            },
        ],
    },
    {
        id: 'partner_006',
        slug: 'job-assistance',
        title: 'Job Assistance',
        shortDescription: 'Launch your career with professional job search support.',
        longDescription: 'Get the job you deserve with our comprehensive career assistance. From CV optimization to interview coaching, we help international students navigate the local job market and land their dream position.',
        icon: 'Briefcase',
        benefits: [
            'Professional CV/resume building',
            'Job market insights',
            'Interview preparation',
            'Networking opportunities',
            'Work permit guidance',
        ],
        tiers: [
            {
                id: 'job_starter',
                name: 'Starter',
                price: 79,
                description: 'DIY job search toolkit',
                deliveryDays: 5,
                features: [
                    'CV template package',
                    'Job portal access guide',
                    'Cover letter templates',
                    'Email support',
                ],
            },
            {
                id: 'job_survival',
                name: 'Survival',
                price: 149,
                description: 'Guided job search',
                deliveryDays: 7,
                features: [
                    'Everything in Starter',
                    'Professional CV review',
                    'LinkedIn profile optimization',
                    '2 job application reviews',
                    'Chat support',
                ],
            },
            {
                id: 'job_comfort',
                name: 'Comfort',
                price: 299,
                description: 'Career launch package',
                deliveryDays: 14,
                isPopular: true,
                features: [
                    'Everything in Survival',
                    'Custom CV writing',
                    'Mock interview session',
                    '5 tailored job applications',
                    'Salary negotiation guide',
                    'Work permit consultation',
                    'Priority support',
                ],
            },
            {
                id: 'job_vip',
                name: 'VIP',
                price: 549,
                description: 'Executive career service',
                deliveryDays: 21,
                features: [
                    'Everything in Comfort',
                    'Dedicated career coach',
                    '3 mock interview sessions',
                    'Unlimited job applications',
                    'Employer introductions',
                    'Networking event access',
                    'Post-hire 30-day support',
                    '24/7 support',
                ],
            },
        ],
    },
];

export function getPartnerServiceBySlug(slug: string): PartnerService | undefined {
    return partnerServices.find((service) => service.slug === slug);
}

export function getAllPartnerServices(): PartnerService[] {
    return partnerServices;
}
